default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432
  # TODO: Use environment variables to set username and password.
  username: postgres
  password: docker

development:
  <<: *default
  database: ma_banque_development

test:
  <<: *default
  database: ma_banque_test

production:
  <<: *default
  database: ma_banque_production
