@startuml

!include styles.puml

title CreateTransaction Transaction Flow (Credit)

(CreateTransaction) << Command >>
(TransactionCreated) << Event >>
(ValidatePendingTransaction) << Reactor >>
(UpdateTransactionStatus) << Command >>
(TransactionStatusUpdated) << Event >>
(CalculateAccountBalance) << Reactor >>
(UpdateAccountBalance) << Command >>
(AccountBalanceUpdated) << Event >>

(CreateTransaction) --> (TransactionCreated)
note right of (CreateTransaction)
    Credit $100
end note
note bottom of (TransactionCreated)
    Default status is PENDING 
end note

(TransactionCreated) <- (ValidatePendingTransaction)

(ValidatePendingTransaction) -> (UpdateTransactionStatus) : Sets status to APPROVED

(TransactionStatusUpdated) <-- (UpdateTransactionStatus)

(TransactionStatusUpdated) -> (CalculateAccountBalance)

(CalculateAccountBalance) -> (UpdateAccountBalance) : 1st

(UpdateAccountBalance) --> (AccountBalanceUpdated)
note bottom of (AccountBalanceUpdated)
    Credit $100 in the
    account current balance
end note

(CalculateAccountBalance) -> (UpdateTransactionStatus) : 2nd sets status to APPLIED

@enduml
