@startuml

!include styles.puml

title Open Account Flow 

(Create) << Command >>
(Created) << Event >>
(ValidatePending) << Reactor >>
(StatusUpdate) << Command >>
(StatusUpdated) << Event >>

(Opens an account) --> (Create)
(Create) --> (Created)
note bottom of (Created)
    Sets status to PENDING
end note

(ValidatePending) --> (Created)

(ValidatePending) --> (StatusUpdate)
(StatusUpdate) --> (StatusUpdated)
note right of (StatusUpdated)
    Sets status to OPENED
end note

@enduml
