@startuml

!include styles.puml

title Open Account Flow 

(Create) << Command >>
(Created) << Event >>
(Creation Validator) << Reactor >>
(Status Update) << Command >>
(Status Updated) << Event >>

(Opens an account) --> (Create)
(Create) --> (Created)
note bottom of (Created)
    Account status is
    PENDING by default
end note

(Creation Validator) --> (Created)

(Creation Validator) ---> (Status Update)
(Status Update) ---> (Status Updated)
note right of (Status Updated)
    Account status
    is now OPENED
end note

@enduml
