@startuml

!include styles.puml

title Create Transaction Flow (Credit)

(Create a transaction) << Action >>
(Create) << Command >>
(Created) << Event >>
(ValidatePending) << Reactor >>
(UpdateStatus) << Command >>
(StatusUpdated) << Event >>
(CalculateAccountBalance) << Reactor >>
(UpdateAccountBalance) << Command >>
(AccountBalanceUpdated) << Event >>

(Create a transaction) -> (Create)
note top of (Create a transaction)
    Credit $100
end note

(Create) --> (Created)
note bottom of (Created)
    Default status is PENDING 
end note
(Created) <-- (ValidatePending) : Listens to
(ValidatePending) -> (UpdateStatus) 
(StatusUpdated) <-- (UpdateStatus)
note right of (UpdateStatus)
    Sets status to APPROVED
end note

(CalculateAccountBalance) --> (StatusUpdated) : Listens to
(CalculateAccountBalance) -> (UpdateAccountBalance)
note right of (UpdateAccountBalance)
    Credit $100 in the
    account current balance
end note
(UpdateAccountBalance) --> (AccountBalanceUpdated) 

@enduml
