@startuml

' See https://plantuml-documentation.readthedocs.io/en/latest/formatting/all-skin-params.html

!define GREY #434343
!define LIGHT_GREY #efefef
!define LIGHT_BLUE #cfe2f3
!define LIGHT_GREEN #d9ead3
!define LIGHT_PURPLE #d9d2e9
!define LIGHT_YELLOW #fff2cc

skinparam note {
    BackgroundColor LIGHT_GREY
    BorderColor GREY
}

skinparam sequence {
    LifeLineBorderColor GREY

    ParticipantBorderColor GREY
    ParticipantBackgroundColor LIGHT_YELLOW

    ParticipantBackgroundColor<< Command >> LIGHT_BLUE
    ParticipantBackgroundColor<< Event >> LIGHT_GREEN
    ParticipantBackgroundColor<< Reactor >> LIGHT_PURPLE
}

skinparam usecase {
    BorderColor GREY
    ArrowColor GREY

    BackgroundColor<< Command >> LIGHT_BLUE
    BackgroundColor<< Event >> LIGHT_GREEN
    BackgroundColor<< Reactor >> LIGHT_PURPLE
}

@enduml
